"""add_is_admin_to_user

Revision ID: 442fc09e88ef
Revises: ce4aa6838ee0
Create Date: 2026-03-08 14:49:00.633070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442fc09e88ef'
down_revision: Union[str, Sequence[str], None] = 'ce4aa6838ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_admin')
    # ### end Alembic commands ###
