"""add_oracle_chat_messages

Revision ID: eb34e2b01582
Revises: 442fc09e88ef
Create Date: 2026-03-14 06:40:35.270075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb34e2b01582'
down_revision: Union[str, Sequence[str], None] = '442fc09e88ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracle_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['oracle_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('ai_interpretations_session_id_fkey'), 'ai_interpretations', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interpretations', 'oracle_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('iching_results_session_id_fkey'), 'iching_results', type_='foreignkey')
    op.create_foreign_key(None, 'iching_results', 'oracle_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('oracle_sessions_user_id_fkey'), 'oracle_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'oracle_sessions', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rune_results_session_id_fkey'), 'rune_results', type_='foreignkey')
    op.create_foreign_key(None, 'rune_results', 'oracle_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tarot_results_session_id_fkey'), 'tarot_results', type_='foreignkey')
    op.create_foreign_key(None, 'tarot_results', 'oracle_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarot_results', type_='foreignkey')
    op.create_foreign_key(op.f('tarot_results_session_id_fkey'), 'tarot_results', 'oracle_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'rune_results', type_='foreignkey')
    op.create_foreign_key(op.f('rune_results_session_id_fkey'), 'rune_results', 'oracle_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'oracle_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('oracle_sessions_user_id_fkey'), 'oracle_sessions', 'user_profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'iching_results', type_='foreignkey')
    op.create_foreign_key(op.f('iching_results_session_id_fkey'), 'iching_results', 'oracle_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'ai_interpretations', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interpretations_session_id_fkey'), 'ai_interpretations', 'oracle_sessions', ['session_id'], ['id'])
    op.drop_table('oracle_chat_messages')
    # ### end Alembic commands ###
